packages/skip-links/tests/site/index.html, packages/skip-links/tests/site/test.scss
Fixes the placement of the skip-links — they need to sit inside the `body`.
=> Fixes markup bug in skip-links.

packages/core/src/sass/_globals.scss
1-char edit. (:
I noticed this because I ended up reusing this function almost as-is, and noticed when SassDoc went over it that it cut the error string short in the reference doc output.
👋
=> Switches out ' to ’ in core’s uikit-space exception error string.

README.md
There was an instance of "modul" which has been updated to "module".
=> Fixing typo in readme file

packages/body/src/sass/_module.scss, packages/core/src/sass/_globals.scss
The selection color is not a11y right now in the dark theme:
I fixed it by mixin it with the right dark theme background color
=> Added appropriate selection color for dark theme

packages/accordion/CHANGELOG.md, packages/accordion/README.md, packages/accordion/package.json, packages/accordion/src/sass/_module.scss
The accordion is flexible and can be used in many ways. Due to this we want `.au-accordion__title` in a `.au-body.au-body--dark` section to get the correct colour chevron.
=> Accordion titles in au-body au-body--dark do not get the correct colour chevron

packages/core/CHANGELOG.md, packages/core/README.md, packages/core/package.json, packages/core/src/sass/_globals.scss
I noticed that overridding or changing the outline offset it was necessary to do this in the dark and light  themes. With this PR you only need to change the offset once in the light theme.
=> Add outline offset to default style, for easier overrides

packages/footer/CHANGELOG.md, packages/footer/README.md, packages/footer/package.json, packages/footer/src/js/react.js, packages/footer/tests/site/index.html
The `role="contentinfo"` is added on footer element to support for older browsers and screen readers that do not expose the `footer` element as a landmark.
See below for justification
https://accessibility.blog.gov.uk/2016/05/27/using-navigation-landmarks/
https://fae.disability.illinois.edu/rulesets/ROLE_9/
http://www.a11ymatters.com/article/intro-html5-sectioning-elements/
https://a11yproject.com/posts/aria-landmark-roles/
=> Added back role=contentinfo in footer

packages/control-input/CHANGELOG.md, packages/control-input/README.md, packages/control-input/package.json, packages/control-input/tests/react/index.js
Since this is an uncontrolled component, passing the `checked` attribute in `<AUradio>` and `<AUcheckbox>` is overriding the `checked` attribute in the DOM. This means the checkbox/radio box will remain checked. If we use `defaultChecked`, it will be checked initially and allow for subsequent updates to be uncontrolled.
fixes #544 
I'm also going to put #548 on hold for now. I believe it's fairly low priority.
=> Fix docs for control inputs with initial checked state

package-lock.json, packages/accordion/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/core/package-lock.json, packages/core/package.json
Auditing `package-lock.json` files given the following alert list:
Seems like it was coming from `browser-sync`, bumped to latest.
=> Resolve lodash vulnerabilities

packages/core/CHANGELOG.md, packages/core/README.md, packages/core/package.json, packages/core/src/sass/_globals.scss
We need to update these so they meet color contrast requirements on an `--alt` background, `#ebebeb`
=> Update error colours to meet contrast on --alt backgrounds

packages/link-list/src/js/react.js
Hi Guys,
As we discussed in Slack channel I'm creating this PR. 
Post from Slack:
> Hi guys, I just found a bug in `AUlinkList` component which it doesn’t respect onClick property that I’m passing. It turns out in the component it compares `typeof onClick === 'function'` but in that line `onClick` variable is undefined.
Thanks
=> fix but that AULinkList not respecting onClick properly

packages/core/CHANGELOG.md, packages/core/README.md, packages/core/package.json, packages/core/src/sass/_globals.scss
As updated in our sketch files in: https://github.com/govau/design-system-site/pull/516 we should add these colours to our `core` module and update `form`.
Issue: #735
=> Add hint colours to `core`

.circleci/config.yml, packages/buttons/package-lock.json
Thanks @gordcorp !
```
cloud.gov.au will start managing this project's CF_* env vars in circleci, and to make
it easier for us we need to have a standard naming convention for environment variables
across all repos we look after.
Nothing should change for this project, this is really just house cleaning to use the
standard names.
The standard naming convention is:
CF_API_PROD
CF_API_STAGING
CF_ORG
CF_PASSWORD_PROD
CF_PASSWORD_STAGING
CF_SPACE
CF_USERNAME
After this has been merged we can remove any CF_* env vars in circleci that
arent in the above list.
```
=> Use cloud.gov.au naming convention for env vars in circleci

packages/card/CHANGELOG.md, packages/card/README.md, packages/card/package.json, packages/card/src/js/react.js
Fixes spacing bug in css classes genereated by react props
=> Fix spacing bug on class names card component

packages/card/CHANGELOG.md, packages/card/README.md, packages/card/package.json, packages/card/src/sass/_module.scss
Forgot to use `unit`. This means a pixel fallback won't be genereated.
=> Use unit instead of rem

packages/searchbox/CHANGELOG.md, packages/searchbox/README.md, packages/searchbox/package.json, packages/searchbox/src/sass/_globals.scss
It was really small previously. It needs to stand out in the absence of text
=> increase size for icon

packages/animate/src/js/module.js
Reported by @kozilla.
Eval appears to be causing failures with Content Security Policy headers.
This is the only place where eval is used.
=> Fix #933 unsafe eval

scripts/helper.js
Fix for `helper.js` causing the scaffolding build process (`npm run scaffolding`) to fail on Windows machines.
=> Hotfix 1001

scripts/helper.js
Fix for `helper.js` causing the component build process (`npm run build`) to fail on Windows machines.
=> HotFix 1007

scripts/helper.js
Added the text **npm** to make it clearer where component versions are being pulled from. Otherwise a situation exists of updated packages in `design-system-components` with newere versions but legacy npm packages referencing older versions.
=> updated label to include the text npm
