govau/design-system-components

packages/body/package.json
=> fixed peerDependency in body

packages/headings/src/sass/module.scss, packages/headings/tests/site/index.html
Provides support for display styles to be used in inline elements + fix for bolding.
=> Fixes headings for usage in inline elements.

helper.js, uikit.json
=> included dependencies intp uikit.json

.templates/new-module/package.json, packages/body/package.json, packages/breadcrumbs/package.json, packages/core/package.json, packages/headings/package.json, packages/link-lists/package.json
=> Changed keyword

manifest.yml, package.json
=> fixed cf path

circle.yml, package.json
=> added compiling assets to circle

packages/header/src/sass/_module.scss
Sorry, forgot to commit this (right when you said ‘don’t commit anything!’). ^_^
=> (#30) Spacing edits to keep things uniform.

circle.yml
=> copy rather than move to we have things to deploy to cf

.templates/new-module/README.md, README.md, packages/body/README.md, packages/breadcrumbs/README.md, packages/callout/README.md, packages/core/README.md, packages/cta-link/README.md, packages/footer/README.md, packages/grid-12/README.md, packages/header/README.md, packages/headings/README.md, packages/inpage-nav/README.md, packages/keyword-list/README.md, packages/link-list/README.md, packages/responsive-media/README.md, packages/skip-link/README.md, packages/tags/README.md, scripts/helper.js
=> added module listing injection into helper, added docs

.templates/new-module/package.json, packages/body/package.json, packages/breadcrumbs/package.json, packages/buttons/package.json, packages/callout/package.json, packages/control-input/package.json, packages/core/package.json, packages/cta-link/package.json, packages/direction-links/package.json, packages/footer/package.json, packages/grid-12/package.json, packages/header/package.json, packages/headings/package.json, packages/inpage-nav/package.json, packages/keyword-list/package.json, packages/link-list/package.json, packages/page-alerts/package.json, packages/responsive-media/package.json, packages/skip-link/package.json, packages/tags/package.json, packages/text-inputs/package.json
=> (#122) fix pancake integration

lerna.json, package.json
So sick of circle... turns out the issue was yarn but still!!! 🐑 
=> trying to fix CI again

packages/core/src/sass/_globals.scss, packages/core/tests/site/test.scss
=> (#132) fixed colour contrast, fixed sass-versioning import

README.md, scripts/helper.js
=> (#136) fixed #136

.templates/index/index.html, packages/buttons/CHANGELOG.md, packages/buttons/README.md, packages/buttons/package.json, packages/buttons/src/sass/_module.scss, packages/buttons/tests/site/index.html
=> (#155) fixed #155, added more styles to index file

packages/footer/tests/site/index.html
=> fixed footer test markup

packages/responsive-media/src/sass/_module.scss
This helps make the SASS a bit more readable.
=> Use the percentage() function instead of magic numbers for responsive videos

packages/body/CHANGELOG.MD, packages/body/README.md, packages/body/package.json, packages/body/src/sass/_module.scss, packages/callout/CHANGELOG.md, packages/callout/README.md, packages/callout/package.json, packages/callout/src/sass/_module.scss, packages/inpage-nav/CHANGELOG.md, packages/inpage-nav/README.md, packages/inpage-nav/package.json, packages/inpage-nav/src/sass/_module.scss, packages/tags/CHANGELOG.md, packages/tags/README.md, packages/tags/package.json, packages/tags/src/sass/_module.scss, scripts/helper.js
=> fixed a11y color contrast issues

README.md
Making it easier to contribute without pressing links multiple times.
=> Updating contributing links on README

scripts/helper.js
Previously the function only got the direct dependencies for a component. We now need it to find all dependencies in the trail.
=> Changing JSON function to get all dependencies

packages/select/README.md
=> Woops wrong PR

README.md, packages/breadcrumbs/src/js/react.js, packages/buttons/src/js/react.js, packages/callout/src/js/react.js, packages/control-input/src/js/react.js, packages/cta-link/src/js/react.js, packages/direction-links/src/js/react.js, packages/footer/src/js/react.js, packages/header/src/js/react.js, packages/inpage-nav/src/js/react.js, packages/keyword-list/src/js/react.js, packages/page-alerts/src/js/react.js, packages/progress-indicator/src/js/react.js, packages/select/src/js/react.js, packages/tags/src/js/react.js, packages/text-inputs/src/js/react.js
=> added documentation link

packages/header/CHANGELOG.md, packages/header/README.md, packages/header/package.json, packages/header/src/js/react.js, packages/header/tests/react/index.js
Fixes https://github.com/govau/designsystem/issues/175
=> HeaderBrand without link now defaults to div

.circleci/config.yml
We used tree to debug and make sure everything was working. It is taking a bit longer than necessary.
=> Remove 🌲 as it takes 11 seconds ⚰️

packages/side-nav/CHANGELOG.md, packages/side-nav/README.md, packages/side-nav/package.json, packages/side-nav/src/js/react.js, packages/side-nav/tests/react/index.js
=> Side navigation active state in react

packages/accordion/CHANGELOG.md, packages/accordion/README.md, packages/accordion/package.json, packages/accordion/src/js/react.js, packages/accordion/tests/react/index.js
=> Revert "Fix/accordion react closed state changes"

packages/footer/README.md, packages/inpage-nav/README.md, packages/main-nav/README.md, packages/side-nav/README.md, packages/skip-link/README.md, packages/skip-link/src/js/react.js
=> Update readme for packages

README.md
fixes https://github.com/govau/designsystem/issues/60
=> Add browser and device support matrix

packages/footer/CHANGELOG.md, packages/footer/README.md, packages/footer/package.json, packages/footer/src/js/react.js, packages/footer/tests/site/index.html
=> Removed footer role contentinfo

packages/control-input/CHANGELOG.md, packages/control-input/README.md, packages/control-input/package.json, packages/control-input/tests/react/index.js
If we use `defaultChecked`, it will be checked initially and allow for subsequent updates to be uncontrolled. fixes #544
=> change control input react prop from 'checked' to 'defaultChecked' 

.circleci/config.yml
@adamzerella you gunslinger, be careful yo 👍
=> -test deployments create test environment

package-lock.json, packages/accordion/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/core/package-lock.json, packages/core/package.json
=> Updated browser-sync and sub dependencies

package-lock.json, package.json
Always the cheeky `node-sass`...
=> Ran `npm audit fix`

scripts/helper.js
=> Removed dev dep check for non-react components

packages/accordion/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/callout/package-lock.json, packages/control-input/package-lock.json, packages/core/package-lock.json, packages/cta-link/package-lock.json, packages/direction-links/package-lock.json, packages/footer/package-lock.json, packages/grid-12/package-lock.json, packages/header/package-lock.json, packages/headings/package-lock.json, packages/inpage-nav/package-lock.json, packages/keyword-list/package-lock.json, packages/link-list/package-lock.json, packages/main-nav/package-lock.json, packages/page-alerts/package-lock.json, packages/progress-indicator/package-lock.json, packages/responsive-media/package-lock.json, packages/select/package-lock.json, packages/skip-link/package-lock.json, packages/tags/package-lock.json, packages/text-inputs/package-lock.json
=> [Security] Bump lodash from 4.17.10 to 4.17.11

package.json
=> Updating contributing docs

FAQ.md
Noted that we don't provide PSD files; updated URL to design-system-site; pointed to templates.
=> Minor content updates

CONTRIBUTING.md, FAQ.md
Thanks @gordongrace for the find!
=> Content updates

packages/footer/CHANGELOG.md, packages/footer/README.md, packages/footer/package.json, packages/footer/src/js/react.js, packages/footer/tests/site/index.html
Remove the word 'navigation' from the aria-label
=> Remove word 'navigation' from aria-label in footer

packages/main-nav/CHANGELOG.md, packages/main-nav/README.md, packages/main-nav/package.json, packages/main-nav/src/js/react.js, packages/main-nav/tests/jquery/index.html, packages/main-nav/tests/site/index.html, scripts/helper.js
Remove the word 'navigation' from aria-label.
=> Remove 'navigation' from aria-label in main nav

packages/form/CHANGELOG.md, packages/form/README.md, packages/form/package.json, packages/form/src/sass/_module.scss
=> Correct AUlabel input element spacing

packages/body/CHANGELOG.md, packages/body/README.md, packages/body/package.json, packages/body/src/sass/_print.scss
=> Change body print `background-color` from #fff to transparent

packages/table/src/js/react.js
The line of code is pretty self explanatory anyway
=> Remove comment causing white space error

packages/form/CHANGELOG.md, packages/form/README.md, packages/form/package.json, packages/form/src/sass/_module.scss, packages/form/tests/site/index.html, packages/table/src/sass/_module.scss
=>  Add margin top to text area preceded by label, hint text or error

packages/table/CHANGELOG.md, packages/table/README.md, packages/table/package.json, packages/table/src/sass/_module.scss
hopefully is the solution to govau/design-system-site#564
=>  Remove js plugin from table package json

packages/main-nav/CHANGELOG.md, packages/main-nav/README.md, packages/main-nav/package.json, packages/main-nav/src/js/module.js, packages/main-nav/src/js/react.js, packages/main-nav/tests/jquery/index.html, packages/main-nav/tests/site/index.html
As per #574. 
Add aria-expanded to menu open button
Will make separate tickets for all other issues on main-nav
Test:
https://design-system-components-featuremain-nav-a11y-test.apps.y.cld.gov.au/packages/main-nav/tests/site/
user and pass: auds
=> Main Navigation - Screen Reader Mobile view 

package-lock.json, packages/accordion/package-lock.json, packages/animate/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/core/package-lock.json
=> Fix vulnerablities components

FAQ.md, README.md, SUPPORT.md
Cleanup, use of SUPPORT.md, remove information duplicated in LICENSE
=> Minor restructure to use GitHub documentation standards

packages/animate/CHANGELOG.md, packages/animate/README.md, packages/animate/package.json
=> Fix #933 - unsafe-eval readme and version bump

package-lock.json, packages/callout/package-lock.json
`node-sass` dependency updated to version `^4.14.0` related to #955
=> Updating node-sass dependency version

packages/breadcrumbs/package-lock.json
updating axios dependency identified as a security issue by dependabot
=> Breadcrumbs axios fix

packages/accordion/package-lock.json, packages/animate/package-lock.json, packages/body/package-lock.json
updating axios dependency identified as a security issue by dependabot
=> axios dependency update

packages/buttons/package-lock.json
updating axios dependency identified as a security issue by dependabot
=> Buttons axios fix

packages/buttons/package-lock.json
updating http proxy dependency identified as a security issue by dependabot
=> dependency update

packages/accordion/package-lock.json
updating http proxy dependency identified as a security issue by dependabot
=> bulk dependency update for http proxy

packages/animate/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/core/package-lock.json
updating http proxy dependency identified as a security issue by dependabot
=> bulk dependency update

packages/accordion/package-lock.json, packages/animate/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/core/package-lock.json
updating http proxy dependencies identified as a security issue by dependabot.
=> Merge Develop into Master

packages/accordion/package-lock.json, packages/animate/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/core/package-lock.json
updating object-path dependency identified as a security issue by dependabot
=> dependency update for object-path

packages/accordion/package-lock.json, packages/animate/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/core/package-lock.json
updating object-path dependency identified as a security issue by dependabot
=> Merging develop to master

packages/accordion/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/callout/package-lock.json
updating multiple dependencies identified as a security issue by dependabot
=> Bulk dependency fix

packages/animate/package-lock.json
updating minimist dependency identified as a security issue by dependabot
=> minimist dependency fix

packages/core/package-lock.json
updating dependencies identified as a security issue by dependabot
=> updating minimist dependencies

packages/animate/package-lock.json, packages/core/package-lock.json
updating dependencies identified as a security issue by dependabot
=> updating dependencies 

packages/accordion/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/callout/package-lock.json
updating minimist dependency identified as a security issue by dependabot
=> bulk minimist dependency update

packages/accordion/package-lock.json, packages/body/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/callout/package-lock.json, packages/core/package-lock.json
Moving from develop to master, updating minimist dependency identified as a security issue by dependabot
=> Merge develop with master

packages/animate/package-lock.json
updating dependency identified as a security issue by dependabot
=> low severity dependency update

packages/animate/package-lock.json, packages/callout/package-lock.json
updating dependency identified as a security issue by dependabot
=> Merge develop to master

packages/buttons/package-lock.json, scripts/helper.js
Moving hotfix #1008 through to `master` closes #1008
=> Moving HotFix #1008 to Master

scripts/helper.js
Fixed `helper.js` fault that I had introduced which was affecting the build scaffolding process.
=> Scaffolding helper.js fix

packages/buttons/package-lock.json, scripts/helper.js
Fixed `helper.js` fault I had introduced which was affecting the build scaffolding process.
=> Scaffolding helper.js fix 

package-lock.json, packages/accordion/package-lock.json, packages/breadcrumbs/package-lock.json, packages/buttons/package-lock.json, packages/callout/package-lock.json
Updated dependabot security advisories for ssri.
=> SSRI dependency update

package-lock.json
Pushed the package-lock.json changes happened after running `npm run bootstrap`. This is to ensure that there will not be any changes on running bootstrap command on master branch before publishing any packages to npm.
=> package-lock.json changes happened with npm run bootstrap
